spring:
  application:
    name: Risk #应用名称,与application.properities中保持一致

  rabbitmq:
    host: 192.168.3.15
    port: 5672
    publisher-confirms: true
    virtual-host: /
    username: admin
    password: admin

#服务注册与发现
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.3.55:10003/eureka/  #Eureka Server

  #服务注册时，在Eureka的实例配置
  #metadata-map.cluster：指定服务集群名称（一个服务集群包括多个app）
  instance:
    preferIpAddress: true
    statusPageUrlPath: /info
    metadata-map:
      cluster: MAIN

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000  #Feign超时时间

#自定义参数
appConfig:
  appName: Risk
  appNameCn: 风控独立模块
  qjqServiceSecret: qjqService-secret_dev
  ruleEngineSecret: ruleEngine-secret_dev
  step0ModelType:
    systemId: 1002    #接入规则引擎时配置的系统ID
    modelType:  1
    modelId:  1
  step1ModelType:
    systemId: 1002
    modelType:  1
    modelId:  2
  step2ModelType:
    systemId: 1002
    modelType: 2
    modelId:  1